name: ics
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  # CACHED IMAGE
  cached_network_image: ^3.2.3

  # FONT SIZE, WIDGETS HEIGHT AND WIDTH
  sizer: ^2.0.15

  # GetCLi
  get: ^4.6.6
  # graphql flutter (API)
  graphql_flutter: ^5.1.2

  # shared_preferences (local storage)
  shared_preferences: ^2.2.0
 # for app icon
  flutter_launcher_icons: ^0.13.1
 
  # for permission
  permission_handler: ^11.0.1
  # for location 

  #FOR UTIL
  logger:

  #FOR On bording
  smooth_page_indicator: ^1.1.0

  cupertino_icons: ^1.0.2
  #For toast message
  bot_toast: ^4.0.4
  connectivity: ^3.0.6
  flutter_bounce: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  im_stepper: ^1.0.1+1
  signature: ^5.4.0

  video_player: ^2.7.2
  image_picker: ^1.0.4
  edge_detection: ^1.1.3
  path_provider: ^2.0.11
  path: ^1.8.2
  pin_code_fields: ^8.0.1
  country_code_picker: ^3.0.0
  form_validator: ^2.1.1
  jwt_decoder: ^2.0.1
  enum_to_string: ^2.0.1
  encrypt: ^5.0.3
  flutter_pdfview: ^1.3.2
  file_picker: ^6.1.1
  dio: ^5.3.4
  animated_segmented_tab_control: ^1.2.0
  timeago: ^3.6.0
  syncfusion_flutter_calendar: ^24.1.47
  timeline_tile: ^2.0.0
  flutter_image_compress: ^2.1.0
  qr_flutter: ^4.1.0
  flutter_typeahead: ^5.2.0
  flutter_cached_pdfview: ^0.4.2
  interval_time_picker: ^2.0.0+5
  flutter_easyrefresh: ^2.2.2
  dotted_line: ^3.2.2
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1













  
dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner:
  flutter_gen_runner:
  #dart run build_runner build
  flutter_test:
    sdk: flutter



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/ics.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"






flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
  fonts:
#jost
    - family: Jost
      fonts:
        - asset: assets/fonts/jost/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/jost/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/jost/Jost-Regular.ttf
          weight: 400


